export interface Club {
  id: string;
  slug: string;
  title: string;
  author: string;
  color: string;
  genre: string;
  tag: string;
  recommender: string;
  reason: string;
  hostName: string;
  hostIntro: string;
  schedule: string;
  location: string;
  maxParticipants: number;
  currentParticipants: number;
  status: "active" | "upcoming";
  description: string;
  emotionTags: string[];
  keyQuestions: string[];
  lat?: number;
  lng?: number;
}

export const ALL_CLUBS: Club[] = [
  // ── 1–6: Featured (메인 히어로 섹션) ──────────────────────────
  {
    id: "c1", slug: "최신간-북토크", title: "최신간 북토크, 핫한 문장들", author: "Quesapience",
    color: "navy", genre: "NEW", tag: "#신간 #트렌드", recommender: "Q5",
    reason: "새벽 세 시에 깨어 있는 사람만 아는 문장이 여기 있습니다.",
    hostName: "정해린", hostIntro: "정답보다 진심을 믿습니다.",
    schedule: "2026년 6월 28일 (토) 오후 3시", location: "서울 서초구 교대역 인근",
    maxParticipants: 8, currentParticipants: 3, status: "active",
    description: "새로 출간된 책들 중 가장 뜨거운 문장들을 함께 읽습니다.",
    emotionTags: ["#불면", "#회복", "#고요"], keyQuestions: ["왜 지금 이 문장인가"],
    lat: 37.4930, lng: 127.0151,
  },
  {
    id: "c2", slug: "다정함의-발명", title: "다정함의 발명", author: "허지영",
    color: "cream", genre: "ESSAY · 산문", tag: "#관계 #사랑", recommender: "지영",
    reason: "사랑은 큰 사건이 아니라 매일 발명되는 작은 다정함이라는 말.",
    hostName: "정해린", hostIntro: "대화는 답을 찾는 과정이 아니라 함께 머무는 과정입니다.",
    schedule: "2026년 6월 14일 (토) 오후 3시", location: "서울 서초구 서초동",
    maxParticipants: 8, currentParticipants: 5, status: "active",
    description: "우리가 일상에서 놓치고 있는 다정함의 순간들을 함께 발견합니다.",
    emotionTags: ["#다정함", "#일상", "#연결"], keyQuestions: ["당신이 가장 다정했던 순간은?", "받은 다정함 중 가장 오래 남은 것은?"],
    lat: 37.4946, lng: 127.0209,
  },
  {
    id: "c3", slug: "혼자라는-감각", title: "혼자라는 감각", author: "주성원",
    color: "rust", genre: "PHILOSOPHY", tag: "#외로움 #인생전환", recommender: "성원",
    reason: "고독을 결핍이 아니라 깊이로 다루는 책.",
    hostName: "서민준", hostIntro: "조용한 사람의 한 문장은 시끄러운 사람의 한 시간보다 길게 남습니다.",
    schedule: "2026년 6월 21일 (토) 오후 2시", location: "서울 마포구 합정동",
    maxParticipants: 6, currentParticipants: 4, status: "active",
    description: "혼자라는 감각이 두려움이 아닌 능력이 되는 공간을 함께 만들어봅니다.",
    emotionTags: ["#고독", "#성장", "#사유"], keyQuestions: ["혼자 있을 때 당신은 무엇을 느끼나요?", "외로움과 고독의 차이는?"],
    lat: 37.5492, lng: 126.9148,
  },
  {
    id: "c4", slug: "아무도-보지-않는-오후", title: "아무도 보지 않는 오후", author: "김범",
    color: "olive", genre: "MEMOIR · 회고", tag: "#창업 #번아웃", recommender: "범",
    reason: "실패한 사람이 아니라, 멈춰본 적 있는 사람의 문장.",
    hostName: "유은재", hostIntro: "대화는 답을 찾는 일이 아니라, 함께 머무는 일입니다.",
    schedule: "2026년 6월 28일 (토) 오후 4시", location: "서울 용산구 한남동",
    maxParticipants: 10, currentParticipants: 3, status: "active",
    description: "번아웃 이후를 살아가는 법을 함께 이야기합니다.",
    emotionTags: ["#회복", "#쉼", "#용기"], keyQuestions: ["당신이 가장 지쳤던 순간은?", "멈추는 것이 용기일 때는 언제인가?"],
    lat: 37.5344, lng: 127.0049,
  },
  {
    id: "c5", slug: "오늘-저녁-당신께", title: "오늘 저녁, 당신께", author: "박상현",
    color: "dusk", genre: "POETRY · 시", tag: "#사랑 #이별", recommender: "상현",
    reason: "시집은 빠르게 읽지 않는 것이라고 가르쳐준 책.",
    hostName: "서민준", hostIntro: "느리게 읽는 것의 가치를 믿습니다.",
    schedule: "2026년 7월 12일 (토) 오후 6시", location: "서울 종로구 부암동",
    maxParticipants: 8, currentParticipants: 6, status: "active",
    description: "한 줄의 시로 한 시간을 이야기하는 모임입니다.",
    emotionTags: ["#느림", "#이별", "#기억"], keyQuestions: ["당신이 가장 오래 머문 문장은?", "이별을 어떻게 기억하나요?"],
    lat: 37.5921, lng: 126.9602,
  },
  {
    id: "c6", slug: "인간이라는-풍경", title: "인간이라는 풍경", author: "한강",
    color: "sage", genre: "NON-FICTION", tag: "#인간 #사유", recommender: "한강",
    reason: "인간을 풍경처럼 멀리서 바라보는 시선.",
    hostName: "유은재", hostIntro: "모든 사람은 이해받아야 할 이유가 있습니다.",
    schedule: "2026년 7월 19일 (토) 오후 2시", location: "서울 마포구 망원동",
    maxParticipants: 10, currentParticipants: 2, status: "active",
    description: "미워하던 사람을 다시 사람으로 보게 만드는 책을 함께 읽습니다.",
    emotionTags: ["#관계", "#용서", "#거리"], keyQuestions: ["당신이 가장 이해하기 힘들었던 사람은?", "미워함이 연민으로 바뀐 경험은?"],
    lat: 37.5558, lng: 126.9073,
  },

  // ── 7–30: 확장 ─────────────────────────────────────────────────
  {
    id: "c7", slug: "제자리로-돌아오는-밤에", title: "제자리로 돌아오는 밤에", author: "서연",
    color: "terra", genre: "ESSAY", tag: "#귀환 #회복", recommender: "서연",
    reason: "길을 잃었다 돌아오는 이야기. 그게 나의 이야기였습니다.",
    hostName: "정해린", hostIntro: "돌아오는 길을 함께 걷습니다.",
    schedule: "2026년 7월 5일 (토) 오후 3시", location: "서울 성동구 성수동",
    maxParticipants: 8, currentParticipants: 8, status: "active",
    description: "길을 잃었다가 제자리로 돌아오는 이야기를 함께 나눕니다.",
    emotionTags: ["#귀환", "#회복", "#방향"], keyQuestions: ["당신이 돌아간 제자리는 어디였나요?"],
  },
  {
    id: "c8", slug: "느리게-읽는-일", title: "느리게 읽는 일", author: "진호",
    color: "smoke", genre: "ESSAY", tag: "#느림 #독서", recommender: "진호",
    reason: "빠르게 읽는 시대에 한 페이지에서 일주일을 머무는 법.",
    hostName: "서민준", hostIntro: "천천히 가는 것이 더 멀리 가는 길입니다.",
    schedule: "2026년 7월 6일 (일) 오후 2시", location: "서울 종로구 삼청동",
    maxParticipants: 6, currentParticipants: 4, status: "active",
    description: "한 문장에 오래 머무는 독서의 기쁨을 나눕니다.",
    emotionTags: ["#느림", "#집중", "#고요"], keyQuestions: ["가장 오래 읽은 책은 무엇인가요?"],
  },
  {
    id: "c9", slug: "어머니의-문장들", title: "어머니의 문장들", author: "지우",
    color: "mauve", genre: "MEMOIR", tag: "#가족 #어머니", recommender: "지우",
    reason: "어머니가 하셨던 말씀 중 지금도 울리는 한 문장.",
    hostName: "유은재", hostIntro: "가족이라는 이름 안에 담긴 무게를 함께 삽니다.",
    schedule: "2026년 7월 12일 (토) 오후 4시", location: "서울 서초구 방배동",
    maxParticipants: 8, currentParticipants: 5, status: "active",
    description: "어머니와의 관계, 그 안의 사랑과 상처를 조심스럽게 꺼냅니다.",
    emotionTags: ["#가족", "#세대", "#사랑"], keyQuestions: ["어머니에게 아직 못 한 말이 있나요?"],
  },
  {
    id: "c10", slug: "흐린-날의-사유", title: "흐린 날의 사유", author: "민재",
    color: "fog", genre: "PHILOSOPHY", tag: "#우울 #사유", recommender: "민재",
    reason: "맑지 않은 날도 사유할 수 있다는 것. 그게 위안이었습니다.",
    hostName: "서민준", hostIntro: "흐린 날엔 더 깊이 생각할 수 있습니다.",
    schedule: "2026년 7월 19일 (토) 오후 3시", location: "서울 마포구 연남동",
    maxParticipants: 6, currentParticipants: 3, status: "active",
    description: "우울과 사유의 경계에서 나누는 철학적 대화.",
    emotionTags: ["#우울", "#철학", "#내면"], keyQuestions: ["흐린 날 당신은 무엇을 하나요?"],
  },
  {
    id: "c11", slug: "아무것도-하지-않는-연습", title: "아무것도 하지 않는 연습", author: "은지",
    color: "ochre", genre: "WELLNESS", tag: "#쉬이 #멈춤", recommender: "은지",
    reason: "아무것도 하지 않는 것이 얼마나 어려운지 처음 알았습니다.",
    hostName: "정해린", hostIntro: "멈추는 연습을 함께 합니다.",
    schedule: "2026년 7월 26일 (토) 오후 2시", location: "서울 용산구 이태원동",
    maxParticipants: 8, currentParticipants: 6, status: "active",
    description: "쉬는 것이 죄처럼 느껴지는 시대에, 멈추는 법을 함께 배웁니다.",
    emotionTags: ["#쉼", "#여백", "#회복"], keyQuestions: ["마지막으로 아무것도 안 한 날은 언제인가요?"],
  },
  {
    id: "c12", slug: "일을-사랑하면서", title: "일을 사랑하면서 일에 지지 않는 법", author: "태우",
    color: "navy", genre: "NON-FICTION", tag: "#번아웃 #일", recommender: "태우",
    reason: "일을 사랑하기 때문에 오히려 더 힘들었던 나에게.",
    hostName: "유은재", hostIntro: "일과 삶의 경계를 다시 그립니다.",
    schedule: "2026년 8월 2일 (토) 오후 4시", location: "서울 강남구 신사동",
    maxParticipants: 10, currentParticipants: 7, status: "active",
    description: "일을 사랑하면서도 무너지지 않는 방법을 함께 찾습니다.",
    emotionTags: ["#번아웃", "#일", "#열정"], keyQuestions: ["당신은 왜 일을 하나요?"],
  },
  {
    id: "c13", slug: "이름-없는-감정들에게", title: "이름 없는 감정들에게", author: "은재",
    color: "cream", genre: "PSYCHOLOGY", tag: "#감정 #내면", recommender: "은재",
    reason: "이름 붙이지 못했던 감정에 비로소 단어를 주었습니다.",
    hostName: "정해린", hostIntro: "감정에 이름을 붙이는 일부터 시작합니다.",
    schedule: "2026년 8월 9일 (토) 오후 3시", location: "서울 서초구 교대역",
    maxParticipants: 8, currentParticipants: 4, status: "active",
    description: "표현되지 못한 감정들을 안전하게 꺼내는 시간.",
    emotionTags: ["#감정", "#언어", "#이해"], keyQuestions: ["아직 이름 붙이지 못한 감정이 있나요?"],
  },
  {
    id: "c14", slug: "수요일-저녁-낭독회", title: "수요일 저녁 낭독회", author: "현우",
    color: "olive", genre: "POETRY · 낭독", tag: "#시 #낭독", recommender: "현우",
    reason: "소리 내어 읽는 순간, 시가 몸 안으로 들어옵니다.",
    hostName: "서민준", hostIntro: "목소리로 읽는 시는 눈으로 읽는 시와 다릅니다.",
    schedule: "2026년 7월 15일 (수) 오후 7시", location: "서울 종로구 익선동",
    maxParticipants: 10, currentParticipants: 9, status: "active",
    description: "매주 수요일 저녁, 시를 소리 내어 읽는 낭독 모임.",
    emotionTags: ["#시", "#낭독", "#목소리"], keyQuestions: ["소리 내어 읽고 싶은 문장이 있나요?"],
  },
  {
    id: "c15", slug: "아버지라는-낯선-사람", title: "아버지라는 낯선 사람", author: "도현",
    color: "rust", genre: "MEMOIR", tag: "#가족 #아버지", recommender: "도현",
    reason: "가장 가까이 있지만 가장 모르는 사람. 아버지.",
    hostName: "유은재", hostIntro: "가족 안의 낯선 사람과 화해하는 이야기.",
    schedule: "2026년 8월 16일 (토) 오후 3시", location: "서울 강동구 천호동",
    maxParticipants: 8, currentParticipants: 5, status: "active",
    description: "아버지와의 관계를 다시 바라보는 시간.",
    emotionTags: ["#가족", "#아버지", "#화해"], keyQuestions: ["아버지에 대해 처음으로 이해한 순간은?"],
  },
  {
    id: "c16", slug: "쓰이지-않는-시간이-있다", title: "쓰이지 않는 시간이 있다", author: "하은",
    color: "sage", genre: "ESSAY", tag: "#시간 #여백", recommender: "하은",
    reason: "무언가를 하지 않아도 되는 시간의 아름다움.",
    hostName: "정해린", hostIntro: "쓰이지 않는 시간이 가장 소중할 수 있습니다.",
    schedule: "2026년 8월 23일 (토) 오후 4시", location: "서울 은평구 응암동",
    maxParticipants: 6, currentParticipants: 2, status: "upcoming",
    description: "목적 없이 보내는 시간의 가치를 함께 탐구합니다.",
    emotionTags: ["#여백", "#시간", "#자유"], keyQuestions: ["당신의 가장 쓸모없었던 시간은?"],
  },
  {
    id: "c17", slug: "어둠-속의-밝은-한-줄", title: "어둠 속의 밝은 한 줄", author: "제이",
    color: "dusk", genre: "POETRY", tag: "#시 #희망", recommender: "제이",
    reason: "가장 어두운 시에서 가장 밝은 한 줄을 발견했습니다.",
    hostName: "서민준", hostIntro: "어둠 속에서도 빛나는 문장들이 있습니다.",
    schedule: "2026년 9월 6일 (토) 오후 6시", location: "서울 노원구 공릉동",
    maxParticipants: 8, currentParticipants: 3, status: "upcoming",
    description: "시 속의 빛나는 문장들을 함께 찾아가는 모임.",
    emotionTags: ["#희망", "#시", "#어둠"], keyQuestions: ["어둠 속에서 당신을 밝혀준 문장은?"],
  },
  {
    id: "c18", slug: "온전하지-않은-시절", title: "온전하지 않은 시절", author: "안녕",
    color: "terra", genre: "MEMOIR", tag: "#청춘 #방황", recommender: "안녕",
    reason: "온전하지 않았던 그 시절이 있었기에 지금이 있습니다.",
    hostName: "유은재", hostIntro: "방황했던 시절을 함께 회고합니다.",
    schedule: "2026년 9월 13일 (토) 오후 3시", location: "서울 영등포구 문래동",
    maxParticipants: 10, currentParticipants: 4, status: "upcoming",
    description: "각자의 온전하지 않았던 시절 이야기를 나눕니다.",
    emotionTags: ["#청춘", "#방황", "#성장"], keyQuestions: ["가장 온전하지 않았던 시절은 언제인가요?"],
  },
  {
    id: "c19", slug: "헤어진-이들의-재회", title: "헤어진 이들의 재회", author: "다연",
    color: "mauve", genre: "NOVEL", tag: "#관계 #이별", recommender: "다연",
    reason: "헤어짐이 끝이 아닐 수 있다는 걸 처음 믿게 해준 소설.",
    hostName: "정해린", hostIntro: "모든 이별은 재회의 씨앗을 품고 있습니다.",
    schedule: "2026년 9월 20일 (토) 오후 4시", location: "서울 강남구 청담동",
    maxParticipants: 8, currentParticipants: 5, status: "upcoming",
    description: "헤어짐과 재회의 의미를 함께 생각합니다.",
    emotionTags: ["#이별", "#재회", "#관계"], keyQuestions: ["다시 만나고 싶은 사람이 있나요?"],
  },
  {
    id: "c20", slug: "도시의-올랜-해", title: "도시의 올랜 해", author: "우재",
    color: "smoke", genre: "URBAN ESSAY", tag: "#도시 #서울", recommender: "우재",
    reason: "서울이라는 도시가 나를 어떻게 만들었는지 생각하게 한 책.",
    hostName: "서민준", hostIntro: "도시와 사람의 관계를 탐구합니다.",
    schedule: "2026년 9월 27일 (토) 오후 3시", location: "서울 성동구 성수동",
    maxParticipants: 10, currentParticipants: 6, status: "upcoming",
    description: "도시가 우리의 내면을 어떻게 형성하는지 함께 읽습니다.",
    emotionTags: ["#도시", "#서울", "#공간"], keyQuestions: ["이 도시가 당신을 어떻게 만들었나요?"],
  },
  {
    id: "c21", slug: "죽음을-읽는-일곱-가지", title: "죽음을 읽는 일곱 가지 시선", author: "혁",
    color: "ink", genre: "PHILOSOPHY", tag: "#죽음 #삶", recommender: "혁",
    reason: "죽음을 읽고 나서야 삶을 다시 보게 되었습니다.",
    hostName: "유은재", hostIntro: "죽음을 이야기해야 삶을 이야기할 수 있습니다.",
    schedule: "2026년 10월 4일 (토) 오후 3시", location: "서울 서초구 반포동",
    maxParticipants: 8, currentParticipants: 2, status: "upcoming",
    description: "죽음이라는 주제를 통해 삶의 의미를 함께 찾습니다.",
    emotionTags: ["#죽음", "#삶", "#의미"], keyQuestions: ["죽음에 대해 처음 진지하게 생각한 순간은?"],
  },
  {
    id: "c22", slug: "난-당신을-잘-모릅니다", title: "난 당신을 잘 모릅니다", author: "재희",
    color: "cream", genre: "ESSAY", tag: "#대화 #관계", recommender: "재희",
    reason: "가장 가까운 사람을 가장 모른다는 것. 그 솔직함이 위안이었습니다.",
    hostName: "정해린", hostIntro: "모름을 인정하는 것이 관계의 시작입니다.",
    schedule: "2026년 10월 11일 (토) 오후 4시", location: "서울 마포구 상수동",
    maxParticipants: 8, currentParticipants: 4, status: "upcoming",
    description: "서로를 다시 알아가는 대화의 시간.",
    emotionTags: ["#대화", "#이해", "#관계"], keyQuestions: ["가장 오래 알았지만 가장 모르는 사람은?"],
  },
  {
    id: "c23", slug: "돈이-말해주지-않는", title: "돈이 말해주지 않는 것들", author: "지훈",
    color: "olive", genre: "NON-FICTION", tag: "#삶 #경제", recommender: "지훈",
    reason: "돈으로 살 수 없는 것들의 목록을 처음으로 적어봤습니다.",
    hostName: "서민준", hostIntro: "돈과 삶, 두 개의 언어를 함께 배웁니다.",
    schedule: "2026년 10월 18일 (토) 오후 3시", location: "서울 강남구 논현동",
    maxParticipants: 10, currentParticipants: 7, status: "upcoming",
    description: "경제 너머의 삶의 가치를 함께 탐구합니다.",
    emotionTags: ["#경제", "#가치", "#삶"], keyQuestions: ["돈으로 살 수 없는 것 중 가장 소중한 건?"],
  },
  {
    id: "c24", slug: "높은-곳의-창가에서", title: "높은 곳의 창가에서", author: "세아",
    color: "fog", genre: "POETRY", tag: "#고독 #시", recommender: "세아",
    reason: "높은 곳에서 내려다보는 시선이 주는 이상한 위안.",
    hostName: "유은재", hostIntro: "높이가 달라지면 보이는 것도 달라집니다.",
    schedule: "2026년 10월 25일 (토) 오후 5시", location: "서울 용산구 서빙고동",
    maxParticipants: 6, currentParticipants: 3, status: "upcoming",
    description: "높은 곳에서 보이는 것들에 관한 시와 대화.",
    emotionTags: ["#고독", "#시선", "#고요"], keyQuestions: ["높은 곳에서 바라본 경험이 있나요?"],
  },
  {
    id: "c25", slug: "다시-걸을-수-있는-사람들", title: "다시 걸을 수 있는 사람들", author: "혜원",
    color: "rust", genre: "MEMOIR", tag: "#회복 #치유", recommender: "혜원",
    reason: "넘어진 후 다시 걷는 법을 배운 이야기.",
    hostName: "정해린", hostIntro: "다시 걷는 것은 처음 걷는 것과 다릅니다.",
    schedule: "2026년 11월 1일 (토) 오후 3시", location: "서울 서초구 교대역",
    maxParticipants: 8, currentParticipants: 4, status: "upcoming",
    description: "회복과 재기의 이야기를 함께 나눕니다.",
    emotionTags: ["#회복", "#재기", "#용기"], keyQuestions: ["당신이 다시 걷기 시작한 순간은?"],
  },
  {
    id: "c26", slug: "외국어로-읽는-한국-소설", title: "외국어로 읽는 한국 소설", author: "명희",
    color: "ochre", genre: "LITERATURE", tag: "#언어 #번역", recommender: "명희",
    reason: "번역된 한국 소설을 읽으며 처음으로 내 언어를 낯설게 보았습니다.",
    hostName: "서민준", hostIntro: "낯선 언어로 읽으면 낯선 감동이 옵니다.",
    schedule: "2026년 11월 8일 (토) 오후 4시", location: "서울 종로구 삼청동",
    maxParticipants: 8, currentParticipants: 3, status: "upcoming",
    description: "번역된 한국 소설을 통해 우리 언어를 새롭게 탐구합니다.",
    emotionTags: ["#언어", "#번역", "#문화"], keyQuestions: ["번역에서 가장 아쉬운 것은 무엇인가요?"],
  },
  {
    id: "c27", slug: "넘어진-자리에서", title: "넘어진 자리에서 주워 든 것들", author: "연우",
    color: "mauve", genre: "MEMOIR", tag: "#실패 #성장", recommender: "연우",
    reason: "실패한 자리에서만 줍게 되는 것들이 있었습니다.",
    hostName: "유은재", hostIntro: "넘어진 자리가 더 많은 것을 가르칩니다.",
    schedule: "2026년 11월 15일 (토) 오후 3시", location: "서울 성동구 왕십리",
    maxParticipants: 10, currentParticipants: 5, status: "upcoming",
    description: "실패와 그 이후의 이야기를 솔직하게 나눕니다.",
    emotionTags: ["#실패", "#회복", "#지혜"], keyQuestions: ["넘어진 자리에서 무엇을 주웠나요?"],
  },
  {
    id: "c28", slug: "밤에만-편지를-씁니다", title: "밤에만 편지를 씁니다", author: "레이",
    color: "dusk", genre: "ESSAY", tag: "#서신 #야간", recommender: "레이",
    reason: "낮에는 못 하는 말을 밤에 편지로 써왔습니다.",
    hostName: "정해린", hostIntro: "밤에만 할 수 있는 이야기들이 있습니다.",
    schedule: "2026년 11월 22일 (토) 오후 7시", location: "서울 마포구 합정동",
    maxParticipants: 8, currentParticipants: 6, status: "upcoming",
    description: "편지라는 형식이 주는 솔직함과 거리감에 대하여.",
    emotionTags: ["#편지", "#야간", "#솔직함"], keyQuestions: ["마지막으로 편지를 쓴 것은 언제인가요?"],
  },
  {
    id: "c29", slug: "자연을-읽는-일요일", title: "자연을 읽는 일요일", author: "소희",
    color: "sage", genre: "NATURE ESSAY", tag: "#생태 #자연", recommender: "소희",
    reason: "자연 안에서 읽는 책은 다르게 읽힙니다.",
    hostName: "서민준", hostIntro: "자연과 책은 둘 다 오래된 언어를 씁니다.",
    schedule: "2026년 11월 29일 (일) 오전 10시", location: "서울 서초구 우면산",
    maxParticipants: 10, currentParticipants: 3, status: "upcoming",
    description: "자연 속에서 함께 책을 읽고 대화하는 야외 모임.",
    emotionTags: ["#자연", "#생태", "#산책"], keyQuestions: ["자연이 당신에게 가르쳐준 것은?"],
  },
  {
    id: "c30", slug: "철학이-필요한-저녁", title: "철학이 필요한 저녁", author: "윤",
    color: "navy", genre: "PHILOSOPHY", tag: "#사유 #철학", recommender: "윤",
    reason: "저녁이 되면 하루의 무게를 철학으로 달래왔습니다.",
    hostName: "유은재", hostIntro: "철학은 어려운 것이 아니라 일상적인 것입니다.",
    schedule: "2026년 12월 6일 (토) 오후 6시", location: "서울 강남구 청담동",
    maxParticipants: 12, currentParticipants: 8, status: "upcoming",
    description: "저녁 식사 후 함께 나누는 가벼운 철학 대화.",
    emotionTags: ["#철학", "#사유", "#저녁"], keyQuestions: ["오늘 가장 철학적인 순간은 언제였나요?"],
  },

  // ── 31–100: 추가 70개 ──────────────────────────────────────────
  { id:"c31", slug:"사랑의-언어-다섯-가지", title:"사랑의 언어 다섯 가지", author:"게리 채프먼", color:"cream", genre:"PSYCHOLOGY", tag:"#관계 #사랑", recommender:"지은", reason:"나의 사랑 언어가 상대방과 달랐다는 것을 알게 됐습니다.", hostName:"정해린", hostIntro:"사랑에도 문법이 있습니다.", schedule:"2026년 7월 4일 (토) 오후 3시", location:"서울 서초구 서초동", maxParticipants:8, currentParticipants:5, status:"active", description:"서로 다른 사랑의 언어를 이해하는 모임.", emotionTags:["#사랑", "#관계", "#이해"], keyQuestions:["당신의 사랑 언어는 무엇인가요?"] },
  { id:"c32", slug:"나는-왜-이렇게-예민한가", title:"나는 왜 이렇게 예민한가", author:"전홍진", color:"mauve", genre:"PSYCHOLOGY", tag:"#예민함 #자아", recommender:"은빈", reason:"예민함이 결점이 아닐 수 있다는 것을 처음 알았습니다.", hostName:"서민준", hostIntro:"예민한 것은 세상을 더 많이 느끼는 것입니다.", schedule:"2026년 7월 11일 (토) 오후 4시", location:"서울 마포구 상수동", maxParticipants:8, currentParticipants:6, status:"active", description:"예민함의 장점과 어려움을 함께 나눕니다.", emotionTags:["#예민함", "#감수성", "#자아"], keyQuestions:["예민함 때문에 힘들었던 순간은?"] },
  { id:"c33", slug:"어른이-된다는-것", title:"어른이 된다는 것", author:"김혜남", color:"olive", genre:"ESSAY", tag:"#성장 #어른", recommender:"승우", reason:"어른이 무엇인지 처음으로 진지하게 생각하게 했습니다.", hostName:"유은재", hostIntro:"어른이 되는 것은 평생의 일입니다.", schedule:"2026년 7월 18일 (토) 오후 3시", location:"서울 종로구 부암동", maxParticipants:10, currentParticipants:4, status:"active", description:"어른이 된다는 것의 의미를 함께 탐구합니다.", emotionTags:["#성장", "#어른", "#책임"], keyQuestions:["당신은 언제 어른이 됐다고 느꼈나요?"] },
  { id:"c34", slug:"경계의-나", title:"경계의 나", author:"정은선", color:"rust", genre:"PSYCHOLOGY", tag:"#경계 #자아", recommender:"현아", reason:"내 경계를 지키는 것이 이기적인 게 아님을 배웠습니다.", hostName:"정해린", hostIntro:"경계는 벽이 아니라 문입니다.", schedule:"2026년 7월 25일 (토) 오후 4시", location:"서울 강남구 신사동", maxParticipants:8, currentParticipants:7, status:"active", description:"건강한 경계 설정에 대한 심리학적 대화.", emotionTags:["#경계", "#자아", "#건강"], keyQuestions:["당신은 경계를 잘 지키고 있나요?"] },
  { id:"c35", slug:"기억의-박물관", title:"기억의 박물관", author:"파울로 코엘료", color:"fog", genre:"NOVEL", tag:"#기억 #과거", recommender:"나리", reason:"기억이 우리를 어떻게 만드는지 생각하게 했습니다.", hostName:"서민준", hostIntro:"기억은 우리가 가진 가장 사적인 박물관입니다.", schedule:"2026년 8월 1일 (토) 오후 3시", location:"서울 마포구 합정동", maxParticipants:8, currentParticipants:3, status:"active", description:"기억과 정체성의 관계를 함께 탐구합니다.", emotionTags:["#기억", "#과거", "#정체성"], keyQuestions:["가장 선명하게 남아있는 기억은?"] },
  { id:"c36", slug:"천천히-나이-드는-연습", title:"천천히 나이 드는 연습", author:"유영만", color:"sage", genre:"ESSAY", tag:"#나이 #시간", recommender:"미정", reason:"나이 드는 것을 두려워하지 않아도 된다는 것.", hostName:"유은재", hostIntro:"천천히 가는 것이 더 오래 갑니다.", schedule:"2026년 8월 8일 (토) 오후 4시", location:"서울 서초구 반포동", maxParticipants:10, currentParticipants:6, status:"active", description:"나이 들어가는 것에 대한 솔직하고 따뜻한 이야기.", emotionTags:["#나이", "#시간", "#성숙"], keyQuestions:["나이 들수록 좋아지는 것은 무엇인가요?"] },
  { id:"c37", slug:"질문이-답이다", title:"질문이 답이다", author:"박정준", color:"terra", genre:"NON-FICTION", tag:"#질문 #사고", recommender:"재민", reason:"질문하는 법을 배우는 것이 답을 배우는 것보다 중요합니다.", hostName:"정해린", hostIntro:"좋은 질문이 좋은 삶을 만듭니다.", schedule:"2026년 8월 15일 (토) 오후 3시", location:"서울 성동구 성수동", maxParticipants:12, currentParticipants:8, status:"active", description:"질문하는 능력을 함께 키우는 모임.", emotionTags:["#질문", "#사고", "#탐구"], keyQuestions:["오늘 가장 좋은 질문을 하셨나요?"] },
  { id:"c38", slug:"불완전한-용기", title:"불완전한 용기", author:"브레네 브라운", color:"ochre", genre:"PSYCHOLOGY", tag:"#용기 #취약함", recommender:"수민", reason:"취약함을 드러내는 것이 용기라는 말이 오래 남았습니다.", hostName:"서민준", hostIntro:"불완전함이 용기의 시작점입니다.", schedule:"2026년 8월 22일 (토) 오후 4시", location:"서울 종로구 삼청동", maxParticipants:8, currentParticipants:5, status:"active", description:"취약함과 용기의 관계를 함께 탐구합니다.", emotionTags:["#용기", "#취약함", "#진정성"], keyQuestions:["당신이 취약함을 드러낸 순간은?"] },
  { id:"c39", slug:"조용히-사는-법", title:"조용히 사는 법", author:"수잔 케인", color:"dusk", genre:"PSYCHOLOGY", tag:"#내향 #조용함", recommender:"호준", reason:"조용한 것이 단점이 아님을 드디어 믿게 됐습니다.", hostName:"유은재", hostIntro:"조용한 사람의 힘을 함께 발견합니다.", schedule:"2026년 8월 29일 (토) 오후 3시", location:"서울 용산구 한남동", maxParticipants:8, currentParticipants:7, status:"active", description:"내향인의 강점을 함께 이야기하는 모임.", emotionTags:["#내향", "#조용함", "#힘"], keyQuestions:["조용함이 당신에게 준 것은?"] },
  { id:"c40", slug:"지금-이-순간을-살아라", title:"지금 이 순간을 살아라", author:"에크하르트 톨레", color:"navy", genre:"SPIRITUALITY", tag:"#현재 #마음챙김", recommender:"보람", reason:"과거와 미래에 살던 나를 지금 여기로 데려온 책.", hostName:"정해린", hostIntro:"지금 이 순간이 유일한 현실입니다.", schedule:"2026년 9월 5일 (토) 오후 4시", location:"서울 마포구 연남동", maxParticipants:10, currentParticipants:4, status:"upcoming", description:"마음챙김과 현재의 의미를 함께 탐구합니다.", emotionTags:["#현재", "#마음챙김", "#존재"], keyQuestions:["지금 이 순간, 당신은 어디에 있나요?"] },
  { id:"c41", slug:"내가-틀릴-수도-있습니다", title:"내가 틀릴 수도 있습니다", author:"비욘 나티코 린데블라드", color:"cream", genre:"MEMOIR", tag:"#겸손 #성찰", recommender:"태이", reason:"내가 틀릴 수 있다는 것을 인정하는 순간 자유로워졌습니다.", hostName:"서민준", hostIntro:"틀릴 수 있음이 지혜의 시작입니다.", schedule:"2026년 9월 12일 (토) 오후 3시", location:"서울 강남구 청담동", maxParticipants:8, currentParticipants:5, status:"upcoming", description:"겸손과 성찰에 관한 이야기를 함께 나눕니다.", emotionTags:["#겸손", "#성찰", "#지혜"], keyQuestions:["당신이 틀렸음을 인정한 순간은?"] },
  { id:"c42", slug:"모든-순간이-너였다", title:"모든 순간이 너였다", author:"하태완", color:"rust", genre:"POETRY", tag:"#사랑 #시", recommender:"예린", reason:"사랑을 이렇게 표현할 수 있다는 것을 처음 알았습니다.", hostName:"정해린", hostIntro:"사랑은 언어 이전의 것입니다.", schedule:"2026년 9월 19일 (토) 오후 5시", location:"서울 서초구 교대역", maxParticipants:8, currentParticipants:6, status:"upcoming", description:"사랑과 그리움에 관한 시를 함께 읽습니다.", emotionTags:["#사랑", "#시", "#그리움"], keyQuestions:["모든 순간이 누군가였던 때가 있나요?"] },
  { id:"c43", slug:"삶이란-무엇인가", title:"삶이란 무엇인가", author:"레프 톨스토이", color:"olive", genre:"PHILOSOPHY", tag:"#삶 #철학", recommender:"민서", reason:"이 질문 앞에 오래 머문 적이 없었는데, 이 책이 머물게 했습니다.", hostName:"유은재", hostIntro:"삶에 대한 질문을 피하지 않는 모임입니다.", schedule:"2026년 9월 26일 (토) 오후 4시", location:"서울 종로구 익선동", maxParticipants:10, currentParticipants:3, status:"upcoming", description:"삶의 의미를 철학적으로 함께 탐구합니다.", emotionTags:["#삶", "#의미", "#철학"], keyQuestions:["삶이란 무엇이라고 생각하나요?"] },
  { id:"c44", slug:"우리가-빛의-속도로-갈-수-없다면", title:"우리가 빛의 속도로 갈 수 없다면", author:"김초엽", color:"fog", genre:"SF", tag:"#SF #미래", recommender:"영진", reason:"과학과 감성이 만나는 지점에서 울었습니다.", hostName:"서민준", hostIntro:"미래를 상상하는 것이 현재를 이해하는 방법입니다.", schedule:"2026년 10월 3일 (토) 오후 3시", location:"서울 성동구 성수동", maxParticipants:10, currentParticipants:7, status:"upcoming", description:"SF 소설이 던지는 인간에 대한 질문을 함께 탐구합니다.", emotionTags:["#SF", "#미래", "#인간"], keyQuestions:["빛의 속도로 갈 수 없다면 어디로 가고 싶나요?"] },
  { id:"c45", slug:"있는-그대로", title:"있는 그대로", author:"칼 로저스", color:"sage", genre:"PSYCHOLOGY", tag:"#수용 #자아", recommender:"하랑", reason:"있는 그대로의 나를 받아들이는 것이 변화의 시작임을 배웠습니다.", hostName:"정해린", hostIntro:"있는 그대로가 충분합니다.", schedule:"2026년 10월 10일 (토) 오후 4시", location:"서울 마포구 망원동", maxParticipants:8, currentParticipants:4, status:"upcoming", description:"자기 수용과 변화의 역설적 관계를 탐구합니다.", emotionTags:["#수용", "#자아", "#변화"], keyQuestions:["있는 그대로의 당신을 받아들이고 있나요?"] },
  { id:"c46", slug:"마음이-어떠세요", title:"마음이 어떠세요", author:"정혜신", color:"terra", genre:"PSYCHOLOGY", tag:"#공감 #치유", recommender:"진", reason:"당신이 어떠냐고 물어보는 사람이 세상에 없었는데, 이 책이 물었습니다.", hostName:"서민준", hostIntro:"마음을 먼저 묻는 것이 모든 관계의 출발입니다.", schedule:"2026년 10월 17일 (토) 오후 3시", location:"서울 강남구 신사동", maxParticipants:8, currentParticipants:6, status:"upcoming", description:"공감과 경청의 기술을 함께 배웁니다.", emotionTags:["#공감", "#치유", "#경청"], keyQuestions:["마지막으로 누군가 마음을 물어봐준 것은 언제인가요?"] },
  { id:"c47", slug:"혼자여서-좋은-날", title:"혼자여서 좋은 날", author:"채민", color:"smoke", genre:"ESSAY", tag:"#혼자 #자유", recommender:"보미", reason:"혼자라는 것이 결핍이 아니라 선택일 수 있습니다.", hostName:"유은재", hostIntro:"혼자를 즐기는 것도 능력입니다.", schedule:"2026년 10월 24일 (토) 오후 4시", location:"서울 용산구 이태원동", maxParticipants:6, currentParticipants:2, status:"upcoming", description:"혼자만의 시간을 풍요롭게 보내는 법에 대한 대화.", emotionTags:["#혼자", "#자유", "#자립"], keyQuestions:["혼자여서 좋은 날은 어떤 날인가요?"] },
  { id:"c48", slug:"말의-무게", title:"말의 무게", author:"박완서", color:"mauve", genre:"ESSAY", tag:"#언어 #말", recommender:"유이", reason:"말 한마디가 얼마나 무거울 수 있는지 다시 배웠습니다.", hostName:"정해린", hostIntro:"말은 세상을 만드는 도구입니다.", schedule:"2026년 10월 31일 (토) 오후 3시", location:"서울 종로구 부암동", maxParticipants:8, currentParticipants:5, status:"upcoming", description:"언어와 말이 가진 힘을 함께 탐구합니다.", emotionTags:["#언어", "#말", "#소통"], keyQuestions:["가장 오래 남은 말 한마디는?"] },
  { id:"c49", slug:"내-몸이-말하는-것들", title:"내 몸이 말하는 것들", author:"가보르 마테", color:"ochre", genre:"PSYCHOLOGY", tag:"#몸 #심신", recommender:"지원", reason:"몸이 마음보다 먼저 말한다는 것을 깨달았습니다.", hostName:"서민준", hostIntro:"몸의 언어를 읽는 법을 배웁니다.", schedule:"2026년 11월 7일 (토) 오후 4시", location:"서울 강남구 청담동", maxParticipants:8, currentParticipants:4, status:"upcoming", description:"심신의 연결에 대한 과학적이고 인간적인 탐구.", emotionTags:["#몸", "#심신", "#건강"], keyQuestions:["당신의 몸은 지금 무엇을 말하고 있나요?"] },
  { id:"c50", slug:"더-나은-실패를-위해", title:"더 나은 실패를 위해", author:"에이미 에드먼슨", color:"dusk", genre:"NON-FICTION", tag:"#실패 #학습", recommender:"도훈", reason:"실패에서 배우는 법을 처음으로 체계적으로 배웠습니다.", hostName:"유은재", hostIntro:"더 나은 실패가 더 나은 성공을 만듭니다.", schedule:"2026년 11월 14일 (토) 오후 3시", location:"서울 마포구 상수동", maxParticipants:10, currentParticipants:6, status:"upcoming", description:"실패를 학습의 기회로 전환하는 방법을 함께 배웁니다.", emotionTags:["#실패", "#학습", "#성장"], keyQuestions:["가장 많이 배운 실패는 무엇인가요?"] },
  { id:"c51", slug:"우리가-원하는-삶", title:"우리가 원하는 삶", author:"김정운", color:"navy", genre:"ESSAY", tag:"#삶 #욕망", recommender:"서준", reason:"내가 진짜 원하는 것이 무엇인지 묻게 해준 책.", hostName:"정해린", hostIntro:"원하는 것을 아는 것이 삶의 절반입니다.", schedule:"2026년 11월 21일 (토) 오후 4시", location:"서울 서초구 서초동", maxParticipants:10, currentParticipants:3, status:"upcoming", description:"진짜 원하는 삶에 대한 정직한 대화.", emotionTags:["#욕망", "#삶", "#선택"], keyQuestions:["당신이 진짜 원하는 삶은 어떤 모습인가요?"] },
  { id:"c52", slug:"침묵의-봄", title:"침묵의 봄", author:"레이첼 카슨", color:"olive", genre:"NATURE", tag:"#환경 #생태", recommender:"지선", reason:"이 책을 읽고 나서 자연을 보는 눈이 달라졌습니다.", hostName:"서민준", hostIntro:"침묵하는 것들의 목소리를 듣는 법.", schedule:"2026년 11월 28일 (토) 오후 3시", location:"서울 강서구 마곡동", maxParticipants:10, currentParticipants:4, status:"upcoming", description:"환경과 생태에 관한 고전을 함께 읽습니다.", emotionTags:["#환경", "#자연", "#생태"], keyQuestions:["자연의 침묵을 들어본 적 있나요?"] },
  { id:"c53", slug:"완벽하지-않아도-좋아", title:"완벽하지 않아도 좋아", author:"브레네 브라운", color:"cream", genre:"PSYCHOLOGY", tag:"#불완전 #자기수용", recommender:"채영", reason:"완벽해야 한다는 강박을 내려놓게 해준 책.", hostName:"유은재", hostIntro:"불완전함을 인정하는 것이 용기입니다.", schedule:"2026년 12월 5일 (토) 오후 4시", location:"서울 종로구 삼청동", maxParticipants:8, currentParticipants:5, status:"upcoming", description:"자기 수용과 취약함에 대한 따뜻한 대화.", emotionTags:["#자기수용", "#불완전", "#용기"], keyQuestions:["완벽하지 않아도 괜찮다고 느낀 순간은?"] },
  { id:"c54", slug:"생각의-탄생", title:"생각의 탄생", author:"로버트 루트번스타인", color:"terra", genre:"NON-FICTION", tag:"#창의 #사고", recommender:"민규", reason:"창의성이 특별한 사람만의 것이 아님을 배웠습니다.", hostName:"정해린", hostIntro:"생각은 연습으로 키워집니다.", schedule:"2026년 12월 12일 (토) 오후 3시", location:"서울 마포구 연남동", maxParticipants:10, currentParticipants:6, status:"upcoming", description:"창의적 사고의 원리를 함께 탐구합니다.", emotionTags:["#창의", "#사고", "#발견"], keyQuestions:["당신의 가장 창의적인 순간은?"] },
  { id:"c55", slug:"관계의-기술", title:"관계의 기술", author:"알랭 드 보통", color:"rust", genre:"PHILOSOPHY", tag:"#관계 #사랑", recommender:"아름", reason:"관계에도 기술이 필요하다는 것을 인정하게 해준 책.", hostName:"서민준", hostIntro:"관계는 예술이기도 하고 기술이기도 합니다.", schedule:"2026년 12월 19일 (토) 오후 4시", location:"서울 용산구 한남동", maxParticipants:8, currentParticipants:4, status:"upcoming", description:"건강한 관계를 위한 철학적 탐구.", emotionTags:["#관계", "#기술", "#사랑"], keyQuestions:["가장 어렵다고 느끼는 관계는 어떤 것인가요?"] },
  { id:"c56", slug:"우리는-모두-죽는다는-것을", title:"우리는 모두 죽는다는 것을", author:"어빈 얄롬", color:"ink", genre:"EXISTENTIAL", tag:"#죽음 #존재", recommender:"상규", reason:"죽음 앞에서야 비로소 삶이 보였습니다.", hostName:"유은재", hostIntro:"죽음을 직면할 때 삶이 살아납니다.", schedule:"2026년 7월 4일 (토) 오후 5시", location:"서울 강남구 논현동", maxParticipants:8, currentParticipants:3, status:"active", description:"실존과 죽음에 관한 철학적 탐구.", emotionTags:["#죽음", "#존재", "#실존"], keyQuestions:["죽음에 대해 가장 두려운 것은 무엇인가요?"] },
  { id:"c57", slug:"서른의-철학", title:"서른의 철학", author:"김은주", color:"mauve", genre:"PHILOSOPHY", tag:"#서른 #나이", recommender:"소담", reason:"서른이 되어서야 읽어야 할 질문들이 여기 있었습니다.", hostName:"정해린", hostIntro:"나이에 따라 철학도 다릅니다.", schedule:"2026년 7월 11일 (토) 오후 4시", location:"서울 성동구 성수동", maxParticipants:8, currentParticipants:7, status:"active", description:"서른이라는 나이의 의미를 함께 탐구합니다.", emotionTags:["#서른", "#나이", "#성찰"], keyQuestions:["서른이 되어 처음 생각한 것은?"] },
  { id:"c58", slug:"나는-나로-살기로-했다", title:"나는 나로 살기로 했다", author:"김수현", color:"sage", genre:"ESSAY", tag:"#자아 #결심", recommender:"예지", reason:"나로 사는 것이 가장 어렵다는 것을 알게 됐습니다.", hostName:"서민준", hostIntro:"나로 사는 것이 가장 용감한 일입니다.", schedule:"2026년 7월 18일 (토) 오후 3시", location:"서울 서초구 교대역", maxParticipants:10, currentParticipants:8, status:"active", description:"자기다운 삶을 살기 위한 결심의 이야기.", emotionTags:["#자아", "#결심", "#용기"], keyQuestions:["나로 살기로 결심한 순간은?"] },
  { id:"c59", slug:"어디서-살-것인가", title:"어디서 살 것인가", author:"유현준", color:"fog", genre:"ARCHITECTURE", tag:"#공간 #건축", recommender:"건우", reason:"공간이 사람을 바꾼다는 것을 건축으로 배웠습니다.", hostName:"유은재", hostIntro:"공간이 곧 삶입니다.", schedule:"2026년 7월 25일 (토) 오후 4시", location:"서울 강동구 천호동", maxParticipants:10, currentParticipants:5, status:"active", description:"공간과 건축이 삶에 미치는 영향을 탐구합니다.", emotionTags:["#공간", "#건축", "#삶"], keyQuestions:["당신이 가장 좋아하는 공간은?"] },
  { id:"c60", slug:"왜-일하는가", title:"왜 일하는가", author:"이나모리 가즈오", color:"terra", genre:"NON-FICTION", tag:"#일 #의미", recommender:"준서", reason:"일의 의미를 잃었을 때 다시 찾게 해준 책.", hostName:"정해린", hostIntro:"왜 일하는지 아는 사람은 지치지 않습니다.", schedule:"2026년 8월 1일 (토) 오후 3시", location:"서울 강남구 청담동", maxParticipants:10, currentParticipants:6, status:"active", description:"일의 의미와 목적에 대한 깊은 대화.", emotionTags:["#일", "#의미", "#목적"], keyQuestions:["당신은 왜 일하나요?"] },
  { id:"c61", slug:"두려움없이-나답게", title:"두려움 없이 나답게", author:"라이언 홀리데이", color:"ochre", genre:"STOICISM", tag:"#철학 #용기", recommender:"태산", reason:"스토아 철학이 이렇게 실용적일 수 있다는 것.", hostName:"서민준", hostIntro:"두려움은 없앨 수 없지만 다룰 수 있습니다.", schedule:"2026년 8월 8일 (토) 오후 4시", location:"서울 마포구 합정동", maxParticipants:10, currentParticipants:4, status:"active", description:"스토아 철학으로 두려움을 마주하는 법.", emotionTags:["#두려움", "#용기", "#철학"], keyQuestions:["지금 가장 두려운 것은 무엇인가요?"] },
  { id:"c62", slug:"사람을-얻는-지혜", title:"사람을 얻는 지혜", author:"데일 카네기", color:"navy", genre:"NON-FICTION", tag:"#관계 #소통", recommender:"진수", reason:"사람과 관계 맺는 법을 처음으로 진지하게 생각했습니다.", hostName:"유은재", hostIntro:"사람을 이해하는 것이 세상을 이해하는 것입니다.", schedule:"2026년 8월 15일 (토) 오후 3시", location:"서울 서초구 서초동", maxParticipants:12, currentParticipants:9, status:"active", description:"인간관계의 지혜를 함께 배우는 모임.", emotionTags:["#관계", "#소통", "#지혜"], keyQuestions:["가장 인간관계가 어려웠던 순간은?"] },
  { id:"c63", slug:"조금씩-아주-조금씩", title:"조금씩, 아주 조금씩", author:"제임스 클리어", color:"cream", genre:"NON-FICTION", tag:"#습관 #성장", recommender:"민찬", reason:"작은 변화가 결국 큰 차이를 만든다는 것을 믿게 됐습니다.", hostName:"정해린", hostIntro:"조금씩 변하는 것이 가장 강력한 변화입니다.", schedule:"2026년 8월 22일 (토) 오후 4시", location:"서울 종로구 익선동", maxParticipants:10, currentParticipants:7, status:"active", description:"습관과 작은 변화의 힘을 함께 탐구합니다.", emotionTags:["#습관", "#성장", "#변화"], keyQuestions:["지금 만들고 싶은 습관은?"] },
  { id:"c64", slug:"사랑하기-때문에", title:"사랑하기 때문에", author:"에리히 프롬", color:"rust", genre:"PHILOSOPHY", tag:"#사랑 #철학", recommender:"은영", reason:"사랑이 감정이 아니라 능력이라는 말이 삶을 바꿨습니다.", hostName:"서민준", hostIntro:"사랑은 배우는 것입니다.", schedule:"2026년 8월 29일 (토) 오후 3시", location:"서울 강남구 신사동", maxParticipants:8, currentParticipants:6, status:"active", description:"에리히 프롬의 사랑론을 함께 읽고 나눕니다.", emotionTags:["#사랑", "#철학", "#능력"], keyQuestions:["당신에게 사랑은 감정인가요, 능력인가요?"] },
  { id:"c65", slug:"어려운-대화", title:"어려운 대화", author:"더글라스 스톤", color:"olive", genre:"COMMUNICATION", tag:"#대화 #갈등", recommender:"유나", reason:"어려운 대화를 피하지 않는 법을 배웠습니다.", hostName:"유은재", hostIntro:"어려운 대화가 가장 필요한 대화입니다.", schedule:"2026년 9월 5일 (토) 오후 4시", location:"서울 성동구 왕십리", maxParticipants:8, currentParticipants:4, status:"upcoming", description:"갈등 상황에서 대화하는 방법을 함께 배웁니다.", emotionTags:["#대화", "#갈등", "#소통"], keyQuestions:["가장 하기 어려운 대화는 어떤 것인가요?"] },
  { id:"c66", slug:"내-마음이-들리나요", title:"내 마음이 들리나요", author:"이미경", color:"fog", genre:"PSYCHOLOGY", tag:"#공감 #마음", recommender:"소이", reason:"내 마음을 들어주는 사람이 없다는 외로움을 함께 나눴습니다.", hostName:"정해린", hostIntro:"마음을 듣는 것이 가장 깊은 관계입니다.", schedule:"2026년 9월 12일 (토) 오후 3시", location:"서울 마포구 연남동", maxParticipants:8, currentParticipants:5, status:"upcoming", description:"진정한 경청과 공감의 기술을 탐구합니다.", emotionTags:["#공감", "#경청", "#마음"], keyQuestions:["마지막으로 마음이 들렸다고 느낀 때는?"] },
  { id:"c67", slug:"철학자의-위로", title:"철학자의 위로", author:"알랭 드 보통", color:"sage", genre:"PHILOSOPHY", tag:"#위로 #철학", recommender:"종민", reason:"철학이 이렇게 따뜻할 수 있다는 것을 처음 알았습니다.", hostName:"서민준", hostIntro:"철학은 삶의 위로가 됩니다.", schedule:"2026년 9월 19일 (토) 오후 4시", location:"서울 강남구 논현동", maxParticipants:10, currentParticipants:6, status:"upcoming", description:"철학으로 삶의 고통을 달래는 방법을 함께 탐구합니다.", emotionTags:["#위로", "#철학", "#고통"], keyQuestions:["철학이 당신을 위로한 적이 있나요?"] },
  { id:"c68", slug:"다시-시작하는-법", title:"다시 시작하는 법", author:"이서연", color:"terra", genre:"MEMOIR", tag:"#재시작 #회복", recommender:"하린", reason:"모든 것이 무너진 후 다시 시작하는 이야기.", hostName:"유은재", hostIntro:"다시 시작하는 것이 처음 시작하는 것보다 용감합니다.", schedule:"2026년 9월 26일 (토) 오후 3시", location:"서울 서초구 반포동", maxParticipants:8, currentParticipants:3, status:"upcoming", description:"새 출발의 두려움과 설렘을 함께 나눕니다.", emotionTags:["#재시작", "#용기", "#회복"], keyQuestions:["다시 시작하기 가장 어려웠던 것은?"] },
  { id:"c69", slug:"지금-여기에-있다는-것", title:"지금 여기에 있다는 것", author:"틱낫한", color:"dusk", genre:"SPIRITUALITY", tag:"#명상 #현재", recommender:"단비", reason:"지금 여기에 있다는 것만으로도 충분하다는 것.", hostName:"정해린", hostIntro:"지금 이 순간이 전부입니다.", schedule:"2026년 10월 3일 (토) 오후 4시", location:"서울 종로구 부암동", maxParticipants:10, currentParticipants:7, status:"upcoming", description:"명상과 현재의 의미를 함께 탐구합니다.", emotionTags:["#명상", "#현재", "#평화"], keyQuestions:["지금 이 순간에 완전히 있어본 적이 있나요?"] },
  { id:"c70", slug:"사람은-왜-거짓말을-하는가", title:"사람은 왜 거짓말을 하는가", author:"댄 에리얼리", color:"smoke", genre:"PSYCHOLOGY", tag:"#진실 #심리", recommender:"진혁", reason:"나 자신의 거짓말을 처음으로 직면하게 됐습니다.", hostName:"서민준", hostIntro:"거짓말을 이해해야 진실을 이해할 수 있습니다.", schedule:"2026년 10월 10일 (토) 오후 3시", location:"서울 강남구 청담동", maxParticipants:8, currentParticipants:4, status:"upcoming", description:"인간의 정직함과 부정직함에 대한 심리학적 탐구.", emotionTags:["#진실", "#거짓", "#심리"], keyQuestions:["당신이 가장 자주 하는 거짓말은?"] },
  { id:"c71", slug:"소유냐-존재냐", title:"소유냐 존재냐", author:"에리히 프롬", color:"ochre", genre:"PHILOSOPHY", tag:"#소유 #존재", recommender:"성하", reason:"소유 방식의 삶에서 존재 방식의 삶으로 전환을 꿈꿨습니다.", hostName:"유은재", hostIntro:"존재하는 것이 소유하는 것보다 풍요롭습니다.", schedule:"2026년 10월 17일 (토) 오후 4시", location:"서울 마포구 상수동", maxParticipants:10, currentParticipants:5, status:"upcoming", description:"프롬의 핵심 철학을 함께 읽고 삶에 적용합니다.", emotionTags:["#소유", "#존재", "#철학"], keyQuestions:["당신은 소유 방식으로 사나요, 존재 방식으로 사나요?"] },
  { id:"c72", slug:"부모와-화해하기", title:"부모와 화해하기", author:"수전 포워드", color:"mauve", genre:"PSYCHOLOGY", tag:"#가족 #화해", recommender:"새봄", reason:"부모를 이해하는 것이 나를 이해하는 것임을 알았습니다.", hostName:"정해린", hostIntro:"화해는 용서가 아니라 이해입니다.", schedule:"2026년 10월 24일 (토) 오후 3시", location:"서울 성동구 성수동", maxParticipants:8, currentParticipants:6, status:"upcoming", description:"부모와의 관계를 새롭게 이해하는 심리학적 탐구.", emotionTags:["#가족", "#화해", "#이해"], keyQuestions:["부모를 이해한 순간이 있었나요?"] },
  { id:"c73", slug:"우리의-시간은-충분한가", title:"우리의 시간은 충분한가", author:"올리버 버크만", color:"navy", genre:"PHILOSOPHY", tag:"#시간 #삶", recommender:"지헌", reason:"시간이 부족하다는 불안을 내려놓게 해준 책.", hostName:"서민준", hostIntro:"시간은 항상 부족하지만 그래도 충분합니다.", schedule:"2026년 10월 31일 (토) 오후 4시", location:"서울 서초구 교대역", maxParticipants:10, currentParticipants:4, status:"upcoming", description:"시간과 삶의 유한성을 함께 직면합니다.", emotionTags:["#시간", "#유한성", "#삶"], keyQuestions:["당신의 시간은 지금 충분한가요?"] },
  { id:"c74", slug:"글쓰기의-최소원칙", title:"글쓰기의 최소원칙", author:"이태준", color:"ink", genre:"WRITING", tag:"#글쓰기 #언어", recommender:"다운", reason:"글 쓰는 법을 처음으로 진지하게 배웠습니다.", hostName:"유은재", hostIntro:"글쓰기는 생각을 명확하게 만드는 도구입니다.", schedule:"2026년 11월 7일 (토) 오후 3시", location:"서울 종로구 익선동", maxParticipants:8, currentParticipants:5, status:"upcoming", description:"글쓰기의 원칙을 함께 배우고 직접 써봅니다.", emotionTags:["#글쓰기", "#언어", "#표현"], keyQuestions:["마지막으로 진심으로 글을 쓴 것은 언제인가요?"] },
  { id:"c75", slug:"타인의-고통", title:"타인의 고통", author:"수전 손택", color:"cream", genre:"NON-FICTION", tag:"#공감 #고통", recommender:"재원", reason:"타인의 고통을 어떻게 봐야 하는지 처음으로 생각했습니다.", hostName:"정해린", hostIntro:"보는 것이 곧 관계 맺는 것입니다.", schedule:"2026년 11월 14일 (토) 오후 4시", location:"서울 마포구 망원동", maxParticipants:8, currentParticipants:3, status:"upcoming", description:"타인의 고통을 마주하는 방법에 대한 철학적 탐구.", emotionTags:["#공감", "#고통", "#시선"], keyQuestions:["타인의 고통을 마주할 때 당신은 어떻게 하나요?"] },
  { id:"c76", slug:"무언가를-만든다는-것", title:"무언가를 만든다는 것", author:"리처드 세넷", color: "rust", genre:"NON-FICTION", tag:"#창작 #장인", recommender:"현태", reason:"손으로 만드는 것의 가치를 다시 발견했습니다.", hostName:"서민준", hostIntro:"만드는 것이 곧 존재하는 것입니다.", schedule:"2026년 11월 21일 (토) 오후 3시", location:"서울 영등포구 문래동", maxParticipants:10, currentParticipants:6, status:"upcoming", description:"창작과 장인 정신에 대한 깊은 탐구.", emotionTags:["#창작", "#장인", "#손"], keyQuestions:["당신이 만든 것 중 가장 소중한 것은?"] },
  { id:"c77", slug:"보이지-않는-것들", title:"보이지 않는 것들", author:"이어령", color:"sage", genre:"ESSAY", tag:"#통찰 #문화", recommender:"승현", reason:"보이지 않는 것들을 보게 해주는 눈을 얻었습니다.", hostName:"유은재", hostIntro:"보이지 않는 것을 보는 것이 지성입니다.", schedule:"2026년 11월 28일 (토) 오후 4시", location:"서울 강남구 신사동", maxParticipants:10, currentParticipants:7, status:"upcoming", description:"한국 문화의 보이지 않는 층위를 함께 탐구합니다.", emotionTags:["#통찰", "#문화", "#이어령"], keyQuestions:["최근에 새롭게 보이기 시작한 것이 있나요?"] },
  { id:"c78", slug:"고전-읽기의-즐거움", title:"고전 읽기의 즐거움", author:"신영복", color:"terra", genre:"LITERATURE", tag:"#고전 #독서", recommender:"경민", reason:"고전이 어렵다고 생각했는데, 이 책이 문을 열어줬습니다.", hostName:"정해린", hostIntro:"고전은 어렵지 않습니다. 낯설 뿐입니다.", schedule:"2026년 12월 5일 (토) 오후 3시", location:"서울 종로구 삼청동", maxParticipants:10, currentParticipants:4, status:"upcoming", description:"고전을 함께 읽으며 그 즐거움을 발견합니다.", emotionTags:["#고전", "#독서", "#인문"], keyQuestions:["가장 읽고 싶은 고전은 무엇인가요?"] },
  { id:"c79", slug:"함께-산다는-것", title:"함께 산다는 것", author:"김현경", color:"fog", genre:"SOCIOLOGY", tag:"#공동체 #관계", recommender:"미래", reason:"함께 사는 것이 무엇인지 다시 생각하게 했습니다.", hostName:"서민준", hostIntro:"함께 삶은 배우는 것입니다.", schedule:"2026년 12월 12일 (토) 오후 4시", location:"서울 서초구 서초동", maxParticipants:10, currentParticipants:5, status:"upcoming", description:"공동체와 함께 삶의 의미를 함께 탐구합니다.", emotionTags:["#공동체", "#관계", "#공존"], keyQuestions:["함께 살기 가장 어려운 순간은?"] },
  { id:"c80", slug:"아름다움이-지구를-구한다", title:"아름다움이 지구를 구한다", author:"도스토옙스키", color:"mauve", genre:"PHILOSOPHY", tag:"#아름다움 #예술", recommender:"나현", reason:"아름다움을 추구하는 것이 도덕적 행위임을 배웠습니다.", hostName:"유은재", hostIntro:"아름다움은 삶의 사치가 아니라 필수입니다.", schedule:"2026년 12월 19일 (토) 오후 3시", location:"서울 강남구 청담동", maxParticipants:8, currentParticipants:3, status:"upcoming", description:"예술과 아름다움이 가진 구원의 힘을 탐구합니다.", emotionTags:["#아름다움", "#예술", "#구원"], keyQuestions:["아름다움이 당신을 구한 적이 있나요?"] },
  { id:"c81", slug:"자유시간", title:"자유시간", author:"권범철", color:"ochre", genre:"ESSAY", tag:"#자유 #여가", recommender:"보선", reason:"자유 시간을 어떻게 보내는지가 그 사람을 말해줍니다.", hostName:"정해린", hostIntro:"자유시간이야말로 가장 중요한 시간입니다.", schedule:"2026년 7월 5일 (일) 오후 4시", location:"서울 종로구 부암동", maxParticipants:8, currentParticipants:4, status:"active", description:"자유 시간의 의미와 활용에 대한 대화.", emotionTags:["#자유", "#여가", "#선택"], keyQuestions:["당신의 자유시간에 무엇을 하나요?"] },
  { id:"c82", slug:"사랑이라는-이름의-감옥", title:"사랑이라는 이름의 감옥", author:"에리카 버거", color:"dusk", genre:"PSYCHOLOGY", tag:"#사랑 #집착", recommender:"가은", reason:"사랑과 집착의 경계를 처음으로 명확히 볼 수 있었습니다.", hostName:"서민준", hostIntro:"건강한 사랑은 자유를 줍니다.", schedule:"2026년 7월 12일 (일) 오후 3시", location:"서울 마포구 합정동", maxParticipants:8, currentParticipants:5, status:"active", description:"건강한 사랑과 집착의 차이를 함께 탐구합니다.", emotionTags:["#사랑", "#집착", "#자유"], keyQuestions:["사랑이 감옥처럼 느껴진 순간이 있나요?"] },
  { id:"c83", slug:"미래를-위한-겸손", title:"미래를 위한 겸손", author:"팀 어번", color:"navy", genre:"NON-FICTION", tag:"#미래 #AI", recommender:"찬호", reason:"AI 시대에 인간이 가져야 할 태도를 생각하게 했습니다.", hostName:"유은재", hostIntro:"미래 앞에서 겸손해야 합니다.", schedule:"2026년 7월 19일 (일) 오후 4시", location:"서울 강남구 논현동", maxParticipants:10, currentParticipants:8, status:"active", description:"AI와 인간의 미래에 대한 열린 대화.", emotionTags:["#AI", "#미래", "#겸손"], keyQuestions:["AI 시대에 인간만이 할 수 있는 것은?"] },
  { id:"c84", slug:"나의-첫-여행", title:"나의 첫 여행", author:"파울로 코엘료", color:"cream", genre:"TRAVEL ESSAY", tag:"#여행 #성장", recommender:"지연", reason:"여행은 장소가 아니라 내면으로 가는 것임을 알았습니다.", hostName:"정해린", hostIntro:"여행은 자신을 발견하는 과정입니다.", schedule:"2026년 7월 26일 (일) 오후 3시", location:"서울 서초구 반포동", maxParticipants:8, currentParticipants:4, status:"active", description:"여행이 가져다준 변화를 함께 나눕니다.", emotionTags:["#여행", "#성장", "#발견"], keyQuestions:["여행이 당신을 바꾼 순간은?"] },
  { id:"c85", slug:"분노를-다루는-법", title:"분노를 다루는 법", author:"타라 브랙", color:"rust", genre:"PSYCHOLOGY", tag:"#분노 #감정", recommender:"태하", reason:"분노를 억누르는 것이 아니라 다루는 법을 배웠습니다.", hostName:"서민준", hostIntro:"분노는 무시할 수 없는 신호입니다.", schedule:"2026년 8월 2일 (일) 오후 4시", location:"서울 용산구 한남동", maxParticipants:8, currentParticipants:5, status:"active", description:"건강하게 분노를 표현하고 다루는 법을 탐구합니다.", emotionTags:["#분노", "#감정", "#표현"], keyQuestions:["분노를 어떻게 다루고 있나요?"] },
  { id:"c86", slug:"인간이라는-숙제", title:"인간이라는 숙제", author:"김형석", color:"olive", genre:"PHILOSOPHY", tag:"#인간 #철학", recommender:"도연", reason:"백 년을 살면서 인간에 대해 배운 것들.", hostName:"유은재", hostIntro:"인간은 평생 풀어야 할 숙제입니다.", schedule:"2026년 8월 9일 (일) 오후 3시", location:"서울 마포구 상수동", maxParticipants:10, currentParticipants:6, status:"active", description:"인간이란 무엇인가라는 근본 질문을 함께 탐구합니다.", emotionTags:["#인간", "#철학", "#삶"], keyQuestions:["인간에 대해 최근 새롭게 배운 것은?"] },
  { id:"c87", slug:"마음의-평화", title:"마음의 평화", author:"조안 홀리팩스", color:"sage", genre:"SPIRITUALITY", tag:"#평화 #명상", recommender:"다빈", reason:"마음의 평화가 성취가 아니라 연습임을 알게 됐습니다.", hostName:"정해린", hostIntro:"평화는 찾는 것이 아니라 만드는 것입니다.", schedule:"2026년 8월 16일 (일) 오후 4시", location:"서울 서초구 서초동", maxParticipants:8, currentParticipants:3, status:"active", description:"내면의 평화를 찾아가는 명상적 탐구.", emotionTags:["#평화", "#명상", "#내면"], keyQuestions:["마음이 가장 평화로웠던 순간은?"] },
  { id:"c88", slug:"우리가-나눈-대화들", title:"우리가 나눈 대화들", author:"박영규", color:"terra", genre:"ESSAY", tag:"#대화 #관계", recommender:"민아", reason:"좋은 대화 한 번이 한 관계 전체를 바꿀 수 있습니다.", hostName:"서민준", hostIntro:"나눈 대화들이 곧 우리의 역사입니다.", schedule:"2026년 8월 23일 (일) 오후 3시", location:"서울 종로구 삼청동", maxParticipants:8, currentParticipants:7, status:"active", description:"대화가 관계를 만드는 방식을 함께 탐구합니다.", emotionTags:["#대화", "#관계", "#기억"], keyQuestions:["가장 오래 남은 대화는 무엇인가요?"] },
  { id:"c89", slug:"모든-것은-지나간다", title:"모든 것은 지나간다", author:"바실리 그로스만", color:"ink", genre:"NOVEL", tag:"#역사 #인간", recommender:"석현", reason:"역사 속에서 인간이란 무엇인지를 묻는 소설.", hostName:"유은재", hostIntro:"지나가는 것을 붙잡으려 하지 않아야 합니다.", schedule:"2026년 8월 30일 (일) 오후 4시", location:"서울 강남구 신사동", maxParticipants:8, currentParticipants:4, status:"active", description:"역사와 인간에 관한 문학적 탐구.", emotionTags:["#역사", "#인간", "#문학"], keyQuestions:["지나간 것 중 가장 아쉬운 것은?"] },
  { id:"c90", slug:"두-번째-인생", title:"두 번째 인생", author:"테레사 수녀", color:"fog", genre:"MEMOIR", tag:"#인생 #전환", recommender:"경화", reason:"인생은 언제든 두 번째로 시작할 수 있습니다.", hostName:"정해린", hostIntro:"두 번째 인생이 첫 번째보다 더 진할 수 있습니다.", schedule:"2026년 9월 6일 (일) 오후 3시", location:"서울 마포구 연남동", maxParticipants:8, currentParticipants:5, status:"upcoming", description:"인생의 두 번째 챕터를 여는 이야기.", emotionTags:["#인생", "#전환", "#시작"], keyQuestions:["당신의 두 번째 인생은 언제 시작됐나요?"] },
  { id:"c91", slug:"행복의-조건", title:"행복의 조건", author:"조지 베일런트", color:"mauve", genre:"NON-FICTION", tag:"#행복 #심리", recommender:"병준", reason:"행복은 성공이 아니라 관계에서 온다는 것.", hostName:"서민준", hostIntro:"행복을 과학으로 이해합니다.", schedule:"2026년 9월 13일 (일) 오후 4시", location:"서울 성동구 성수동", maxParticipants:10, currentParticipants:6, status:"upcoming", description:"하버드 연구로 보는 행복의 조건을 탐구합니다.", emotionTags:["#행복", "#관계", "#연구"], keyQuestions:["당신의 행복 조건은 무엇인가요?"] },
  { id:"c92", slug:"당신이-옳다", title:"당신이 옳다", author:"정혜신", color:"ochre", genre:"PSYCHOLOGY", tag:"#공감 #치유", recommender:"예나", reason:"당신이 옳다는 말을 처음으로 진심으로 들은 것 같았습니다.", hostName:"유은재", hostIntro:"당신의 경험이 틀린 것이 아닙니다.", schedule:"2026년 9월 20일 (일) 오후 3시", location:"서울 강남구 청담동", maxParticipants:8, currentParticipants:7, status:"upcoming", description:"공감과 치유의 심리학을 함께 배웁니다.", emotionTags:["#공감", "#치유", "#옳음"], keyQuestions:["당신의 감정이 옳다고 느낀 순간은?"] },
  { id:"c93", slug:"심야-식당", title:"심야 식당", author:"아베 야로", color:"dusk", genre:"MANGA ESSAY", tag:"#음식 #이야기", recommender:"선아", reason:"음식 한 그릇에 담긴 인생 이야기들.", hostName:"정해린", hostIntro:"음식은 가장 오래된 이야기입니다.", schedule:"2026년 9월 27일 (일) 오후 6시", location:"서울 마포구 합정동", maxParticipants:10, currentParticipants:8, status:"upcoming", description:"음식과 이야기가 만나는 밤의 모임.", emotionTags:["#음식", "#이야기", "#밤"], keyQuestions:["가장 기억에 남는 음식과 그 이야기는?"] },
  { id:"c94", slug:"오래된-미래", title:"오래된 미래", author:"헬레나 노르베리 호지", color:"olive", genre:"SOCIOLOGY", tag:"#지속가능 #공동체", recommender:"자연", reason:"오래된 것에서 미래를 찾는 역설적 지혜.", hostName:"서민준", hostIntro:"오래된 것이 가장 새로운 것일 수 있습니다.", schedule:"2026년 10월 4일 (일) 오후 3시", location:"서울 서초구 우면산", maxParticipants:10, currentParticipants:3, status:"upcoming", description:"지속 가능한 미래를 위한 전통의 지혜를 탐구합니다.", emotionTags:["#지속가능", "#전통", "#미래"], keyQuestions:["오래된 것에서 배운 가장 중요한 것은?"] },
  { id:"c95", slug:"감사의-힘", title:"감사의 힘", author:"로버트 에먼스", color:"cream", genre:"PSYCHOLOGY", tag:"#감사 #긍정", recommender:"하솔", reason:"감사가 단순한 감정이 아니라 삶의 태도임을 알았습니다.", hostName:"유은재", hostIntro:"감사할 줄 아는 것이 행복의 기술입니다.", schedule:"2026년 10월 11일 (일) 오후 4시", location:"서울 종로구 익선동", maxParticipants:8, currentParticipants:5, status:"upcoming", description:"감사의 심리학과 실천을 함께 탐구합니다.", emotionTags:["#감사", "#긍정", "#행복"], keyQuestions:["오늘 감사한 것 세 가지는?"] },
  { id:"c96", slug:"디지털-미니멀리즘", title:"디지털 미니멀리즘", author:"칼 뉴포트", color:"navy", genre:"NON-FICTION", tag:"#디지털 #집중", recommender:"승민", reason:"스마트폰을 내려놓기 위해 용기가 필요했습니다.", hostName:"정해린", hostIntro:"덜 연결될수록 더 많이 연결됩니다.", schedule:"2026년 10월 18일 (일) 오후 3시", location:"서울 성동구 왕십리", maxParticipants:10, currentParticipants:6, status:"upcoming", description:"디지털 기기와 건강한 관계를 맺는 방법을 탐구합니다.", emotionTags:["#디지털", "#집중", "#여백"], keyQuestions:["스마트폰 없이 하루를 보낸 적이 있나요?"] },
  { id:"c97", slug:"경계선", title:"경계선", author:"클라우드-타운센드", color:"smoke", genre:"PSYCHOLOGY", tag:"#경계 #관계", recommender:"서하", reason:"경계선을 긋는 것이 사랑을 거부하는 것이 아님을 알았습니다.", hostName:"서민준", hostIntro:"경계선은 관계를 보호하는 것입니다.", schedule:"2026년 10월 25일 (일) 오후 4시", location:"서울 강남구 신사동", maxParticipants:8, currentParticipants:4, status:"upcoming", description:"건강한 경계 설정과 관계 회복을 함께 탐구합니다.", emotionTags:["#경계선", "#관계", "#건강"], keyQuestions:["당신이 긋지 못한 경계선은?"] },
  { id:"c98", slug:"글쓰기가-나를-구했다", title:"글쓰기가 나를 구했다", author:"줄리아 카메론", color:"rust", genre:"WRITING", tag:"#글쓰기 #창작", recommender:"나단", reason:"매일 아침 세 페이지를 쓰면서 나를 다시 찾았습니다.", hostName:"유은재", hostIntro:"글쓰기는 자기 발견의 가장 직접적인 방법입니다.", schedule:"2026년 11월 1일 (일) 오후 3시", location:"서울 마포구 연남동", maxParticipants:8, currentParticipants:5, status:"upcoming", description:"아침 글쓰기와 창의성 회복에 관한 탐구.", emotionTags:["#글쓰기", "#창작", "#치유"], keyQuestions:["글쓰기가 당신을 도운 순간이 있나요?"] },
  { id:"c99", slug:"탐정소설처럼-읽는-철학", title:"탐정소설처럼 읽는 철학", author:"리처드 왓슨", color:"terra", genre:"PHILOSOPHY", tag:"#철학 #재미", recommender:"준환", reason:"철학을 이렇게 재미있게 읽을 수 있다는 것.", hostName:"정해린", hostIntro:"철학은 삶의 수수께끼를 푸는 것입니다.", schedule:"2026년 11월 8일 (일) 오후 4시", location:"서울 종로구 삼청동", maxParticipants:10, currentParticipants:6, status:"upcoming", description:"탐정소설처럼 흥미진진하게 철학을 탐구합니다.", emotionTags:["#철학", "#재미", "#탐구"], keyQuestions:["철학이 재미있었던 순간이 있나요?"] },
  { id:"c100", slug:"오늘도-살아냈다", title:"오늘도 살아냈다", author:"박정은", color:"sage", genre:"ESSAY", tag:"#일상 #생존", recommender:"하나", reason:"오늘 하루를 살아냈다는 것만으로도 충분합니다.", hostName:"서민준", hostIntro:"살아내는 것도 대단한 일입니다.", schedule:"2026년 11월 15일 (일) 오후 3시", location:"서울 서초구 교대역", maxParticipants:8, currentParticipants:4, status:"upcoming", description:"오늘을 살아내는 것의 의미를 함께 나눕니다.", emotionTags:["#일상", "#생존", "#회복"], keyQuestions:["오늘을 살아내게 한 것은 무엇인가요?"] },
];

// LandingPage BookClub 형식으로 변환
export function toLandingClub(c: Club) {
  return {
    slug: c.slug,
    title: c.title,
    author: c.author,
    color: c.color,
    genre: c.genre,
    tag: c.tag,
    recommender: c.recommender,
    reason: c.reason,
    emotionTags: c.emotionTags,
    hostName: c.hostName,
    hostIntro: c.hostIntro,
    schedule: c.schedule,
    location: c.location,
    maxParticipants: c.maxParticipants,
    currentParticipants: c.currentParticipants,
    description: c.description,
    sessionDates: [{ date: c.schedule.slice(0, 10).replace(/년 /, "-").replace(/월 /, "-").replace(/일.*/, ""), topic: c.emotionTags[0] ?? "" }],
    lat: c.lat,
    lng: c.lng,
  };
}

// BookClubClient DB 형식으로 변환
export function toBookClubCard(c: Club) {
  return {
    id: c.id,
    slug: c.slug,
    title: c.title,
    author: c.author,
    color: c.color,
    genre: c.genre,
    tag: c.tag,
    host_name: c.hostName,
    host_intro: c.hostIntro,
    schedule: c.schedule,
    location: c.location,
    max_participants: c.maxParticipants,
    current_participants: c.currentParticipants,
    status: c.status,
    description: c.description,
    emotion_tags: c.emotionTags,
    key_questions: c.keyQuestions,
    why_this_book: c.reason,
    session_dates: [{ date: "", topic: c.emotionTags[0] ?? "" }],
  };
}
